services:
  telegram-bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: telegram-bot
    env_file:
      - .env
    environment:
      - TZ=${TZ:-Asia/Tehran}
      - DB_PATH=/app/data/data.db
    volumes:
      - ./data:/app/data
    restart: unless-stopped